// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdM086jV3EMKkuV3ZGhSwxT9F_v7xcR6I',
    appId: '1:395880458072:web:7fe08035359c9fe728a72d',
    messagingSenderId: '395880458072',
    projectId: 'household-vtt-fe50d',
    authDomain: 'household-vtt-fe50d.firebaseapp.com',
    storageBucket: 'household-vtt-fe50d.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9TBfsKpEVmU4lgv1YWKj_1Fq43pov5RY',
    appId: '1:395880458072:ios:bcaa556ea84fdfa328a72d',
    messagingSenderId: '395880458072',
    projectId: 'household-vtt-fe50d',
    storageBucket: 'household-vtt-fe50d.firebasestorage.app',
    iosBundleId: 'com.lorenzopreti.householdVtt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdM086jV3EMKkuV3ZGhSwxT9F_v7xcR6I',
    appId: '1:395880458072:web:c628505257bc28d228a72d',
    messagingSenderId: '395880458072',
    projectId: 'household-vtt-fe50d',
    authDomain: 'household-vtt-fe50d.firebaseapp.com',
    storageBucket: 'household-vtt-fe50d.firebasestorage.app',
  );
}
